import os

os.system("sudo apt-get install cutadapt")
os.system("sudo apt-get install build-essential")
os.system("sudo apt-get install zlib1g")
os.system("sudo apt-get install zlib1g-dev")
os.system("sudo apt-get install default-jre")
#os.system("sudo apt-get install python3-pip")
#os.system("sudo apt-get install python3-dev")
#os.system("sudo apt-get install libjpeg-dev")
#os.system("sudo apt-get install libtiff-dev")
#os.system("sudo apt-get install libsdl1.2-dev")
#os.system("sudo apt-get install libgstream")
#os.system("sudo apt-get install libnotify-dev")
#os.system("sudo apt-get install freeglut")
#os.system("sudo apt-get install libgtk-3-dev")
#os.system("sudo apt-get install libwebkitgtk-3.0-dev")
#os.system("sudo apt-get install python3-distutils")
#os.system("sudo apt-get install python3-dev")
#os.system("sudo pip3 install python-config")
#os.system("sudo pip3 install -U wxPython")
#os.system("sudo pip install -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-16.04 wxPython")
#os.system("wget -q -O /tmp/libpng12.deb http://mirrors.kernel.org/ubuntu/pool/main/libp/libpng/libpng12-0_1.2.54-1ubuntu1_amd64.deb   && sudo dpkg -i /tmp/libpng12.deb   && sudo rm /tmp/libpng12.deb")

os.system("sed -i -e 's/CC_OPTS    = -g -Wall -D__USE_FIXED_PROTOTYPES__/CC_OPTS = -g -Wall -D__USE_FIXED_PROTOTYPES_ -fpermissive/' software/primer3/src/Makefile")

os.system("make -C software/primer3/src/")
os.system("make -C software/cdhit")
os.system("make -C software/FLASH-1.2.11")
